In [2]:
import torch

In [3]:
torch.__version__

'2.2.2'

In [4]:
scalar = torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
matrix = torch.tensor([[7,8],[9,8]])
matrix

tensor([[7, 8],
        [9, 8]])

In [13]:
matrix.ndim

2

In [16]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor.shape

torch.Size([3, 3])

In [17]:
tensor.dim

<function Tensor.dim>

In [18]:
tensor.ndim

2

In [19]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.6582, 0.5856, 0.2345, 0.3127],
         [0.2789, 0.8685, 0.8011, 0.4014],
         [0.3443, 0.7387, 0.1282, 0.2143]]),
 torch.float32)

In [20]:
random_image_size = torch.rand(size=(224,224,3))
random_image_size.shape, random_image_size.ndim


(torch.Size([224, 224, 3]), 3)

In [21]:
zeros = torch.zeros(size=(1,3,4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
zero_ten = torch.arange(start=0, end=10, step=1)
zero_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros= torch.zeros_like(input=zero_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
torch.cuda

<module 'torch.cuda' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/cuda/__init__.py'>

In [25]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                   dtype=None,
                                   device=None,
                                   requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor.dtype, float_16_tensor.device

(torch.float16, device(type='cpu'))

In [29]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"shape: {some_tensor.shape}")
print(f"dtype: {some_tensor.dtype}")
print(f"device: {some_tensor.device}")

tensor([[0.7926, 0.8430, 0.9210, 0.2302],
        [0.9932, 0.7918, 0.6527, 0.1386],
        [0.7937, 0.2693, 0.3440, 0.5462]])
shape: torch.Size([3, 4])
dtype: torch.float32
device: cpu


In [31]:
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor = tensor - 10
tensor

tensor([-19, -18, -17])

In [34]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
tensor @ tensor

tensor(14)

In [37]:
torch.matmul(tensor, tensor)


tensor(14)

In [42]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=6)

x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]], dtype=torch.float32)

tensorB = torch.tensor([[7,10],
                  [8,11],
                  [9,12]], dtype=torch.float32)

output = linear(x.T)
print(f"Shape: {x.shape}")
print(output)
print(f"OutputShape: {output.shape}")


Shape: torch.Size([3, 2])
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)
OutputShape: torch.Size([2, 6])


In [44]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [46]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [48]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [50]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [56]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [58]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [59]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [60]:
x_org = torch.rand(size=(224,224,3))

x_per = x_org.permute(2,0,1)

x_org.shape, x_per.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [61]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
x[:,0]

tensor([[1, 2, 3]])

In [70]:
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
import numpy as np

In [80]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [81]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [82]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
rand_A = torch.rand(3,4)
rand_B = torch.rand(3,4)

print(f"A: {rand_A}")
print(f"B: {rand_B}")
print(f"A == B ?: {rand_A == rand_B}")

A: tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
B: tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])
A == B ?: tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
rand_C = torch.rand(3,4)

torch.random.manual_seed(seed=RANDOM_SEED)
rand_D = torch.rand(3,4)

print(f"C: {rand_C}")
print(f"D: {rand_D}")
print(f"C == D ?: {rand_C == rand_D}")

C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
C == D ?: tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [85]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [86]:
device = torch.device('mps:0' if torch.backends.mps.is_available() else 'cpu')


In [87]:
device

device(type='mps', index=0)

In [88]:
print(f"MPS 장치가 사용 가능한지: {torch.backends.mps.is_available()}") # True 여야 합니다.

MPS 장치가 사용 가능한지: True


In [89]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor_on_mps = tensor.to(device)
tensor_on_mps

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [ ]:
# Practice  

In [93]:
rand_tens = torch.rand(size=(7,7))
rand_tens.shape

torch.Size([7, 7])

In [95]:
rand_tens2 = torch.rand(size=(1,7))

torch.mm(rand_tens, rand_tens2.T)

tensor([[1.1717],
        [0.9437],
        [0.9601],
        [0.8217],
        [1.0516],
        [0.6525],
        [0.3525]])

In [99]:
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
rand_tens = torch.rand(size=(7,7))
rand_tens2 = torch.rand(size=(1,7)).T
res = torch.mm(rand_tens, rand_tens2)
res

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [102]:
torch.manual_seed(1234)
tens1 = torch.rand(size=(2,3))
tens2 = torch.rand(size=(2,3))

gpu_tens1 = tens1.to(device)
gpu_tens2 = tens2.to(device)

gpu_tens1, gpu_tens2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))

In [106]:
res = torch.mm(gpu_tens1, gpu_tens2.T)
res

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

In [108]:
res.max(), res.min()

(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

In [109]:
torch.manual_seed(7)
tens10 = torch.rand(size=(1,1,1,10))

tens10, tens10.squeeze()


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))